<?php
/**
 * Pterodactyl - Traduzido PT-BR
 * Traduzido pelo PatrickHG7
 * Discord: PatrickHG7#5249
 * Qualquer bug reporte para o patrick
 */

return [
    'email' => 'Email',
    'email_address' => 'Endereço de e-mail',
    'user_identifier' => 'Usuario ou Email',
    'password' => 'Senha',
    'new_password' => 'Nova senha',
    'confirm_password' => 'Confirme a nova senha',
    'login' => 'Logar',
    'home' => 'Inicio',
    'servers' => 'Servidores',
    'id' => 'ID',
    'name' => 'Nome',
    'node' => 'Node',
    'connection' => 'Conexão',
    'memory' => 'Memoria',
    'cpu' => 'CPU',
    'disk' => 'Disco',
    'status' => 'Status',
    'search' => 'Pesquisa',
    'suspended' => 'Suspenso',
    'account' => 'Conta',
    'security' => 'Segurança',
    'ip' => 'Endereço de IP',
    'last_activity' => 'Ultima atividade',
    'revoke' => 'Revogar',
    '2fa_token' => 'Token de autenticação',
    'submit' => 'Enviar',
    'close' => 'Fechar',
    'settings' => 'Configurações',
    'configuration' => 'Configuração',
    'sftp' => 'SFTP',
    'databases' => 'Bancos de dados',
    'memo' => 'Memorando',
    'created' => 'Criado',
    'expires' => 'Expira',
    'public_key' => 'Token',
    'api_access' => 'Acesso Api',
    'never' => 'Nunca',
    'sign_out' => 'Sair',
    'admin_control' => 'Controle de Admin',
    'required' => 'Requeridos',
    'port' => 'Porta',
    'username' => 'Usuario',
    'database' => 'Base de dados',
    'new' => 'Novo',
    'danger' => 'Perigo',
    'create' => 'Criar',
    'select_all' => 'Selecionar tudo',
    'select_none' => 'Selecione nenhum',
    'alias' => 'Apelido',
    'primary' => 'Primário',
    'make_primary' => 'Tornar Primário',
    'none' => 'Nenhum',
    'cancel' => 'Cancelar',
    'created_at' => 'Criado em',
    'action' => 'Açao',
    'data' => 'Data',
    'queued' => 'Na fila',
    'last_run' => 'Última corrida',
    'next_run' => 'Próxima execução',
    'not_run_yet' => 'Ainda não executado',
    'yes' => 'Sim',
    'no' => 'Não',
    'delete' => 'Excluir',
    '2fa' => '2FA',
    'logout' => 'Sair',
    'admin_cp' => 'Painel de controle do administrador',
    'optional' => 'Opcional',
    'read_only' => 'Somente leitura',
    'relation' => 'Relação',
    'owner' => 'Dono',
    'admin' => 'Admin',
    'subuser' => 'Sub-usuario',
    'captcha_invalid' => 'O captcha fornecido é inválido.',
    'tasks' => 'Tarefas',
    'seconds' => 'Segundos',
    'minutes' => 'Minutos',
    'under_maintenance' => 'Em manutenção',
    'days' => [
        'sun' => 'Domigo',
        'mon' => 'Segunda-feira',
        'tues' => 'Terça-feira',
        'wed' => 'Quarta-feira',
        'thurs' => 'Quinta-feira',
        'fri' => 'Sexta-feira',
        'sat' => 'Sabado',
    ],
    'last_used' => 'Usado por último',
    'enable' => 'Habilitar',
    'disable' => 'Desabilitar',
    'save' => 'Salvar',
    'copyright' => '&copy; 2015 - :year Pterodactyl Software',
];
